import React, { useEffect, useMemo, useRef, useState } from 'react';
import { collection, deleteDoc, doc, getDoc, onSnapshot, query, serverTimestamp, setDoc, updateDoc, where } from 'firebase/firestore';
import { db, initAuth } from './firebase';
import { ICE_SERVERS, generateRoomId } from './webrtc';
import { ArrowRight, Check, Copy, Link2, Loader2, Mic, MicOff, PhoneOff, Shield, Sparkles, UserCheck, UserRound, UserX, Users, Video, VideoOff, Wifi, X } from 'lucide-react';

const SIGNAL_TYPES = new Set(['offer', 'answer', 'candidate']);

export default function MeetingApp() {
  const [user,setUser]=useState(null),[ready,setReady]=useState(false),[roomId,setRoomId]=useState(''),[name,setName]=useState(''),[host,setHost]=useState(false),[screen,setScreen]=useState('home');
  const [localStream,setLocalStream]=useState(null),[remoteStreams,setRemoteStreams]=useState({}),[participants,setParticipants]=useState({}),[peerStatus,setPeerStatus]=useState({}),[pending,setPending]=useState([]);
  const [mic,setMic]=useState(true),[cam,setCam]=useState(true),[copied,setCopied]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const userRef=useRef(null),roomRef=useRef(''),streamRef=useRef(null),peersRef=useRef({}),queuesRef=useRef({}),requestUnsubRef=useRef(null),retryRef=useRef({});
  useEffect(()=>{userRef.current=user},[user]); useEffect(()=>{roomRef.current=roomId},[roomId]);

  useEffect(()=>{let alive=true; initAuth().then(async u=>{if(!alive)return;userRef.current=u;setUser(u);setReady(true);const id=new URLSearchParams(location.search).get('room')?.trim().toLowerCase();if(!id)return;roomRef.current=id;setRoomId(id);try{const s=await getDoc(doc(db,'rooms',id));if(s.exists()&&s.data().hostUid===u.uid)setHost(true)}catch{}setScreen('join')}).catch(e=>{console.error(e);setError('Could not connect to the meeting service.')});return()=>{alive=false}},[]);

  const status=(id,v)=>setPeerStatus(x=>({...x,[id]:v}));
  const signal=async(to,type,payload={})=>{const u=userRef.current,r=roomRef.current;if(!u||!r||!SIGNAL_TYPES.has(type))return;await setDoc(doc(collection(db,'rooms',r,'signals')),{from:u.uid,to,type,...payload,createdAt:serverTimestamp()})};
  const closePeer=(id)=>{const pc=peersRef.current[id];if(pc){try{pc.close()}catch{}delete peersRef.current[id]}delete queuesRef.current[id];delete retryRef.current[id];setRemoteStreams(x=>{const n={...x};delete n[id];return n});setPeerStatus(x=>{const n={...x};delete n[id];return n})};

  const createPeer=(peerId)=>{
    if(peersRef.current[peerId])return peersRef.current[peerId];
    const u=userRef.current,s=streamRef.current;if(!u||!s)return null;
    const pc=new RTCPeerConnection(ICE_SERVERS); peersRef.current[peerId]=pc; queuesRef.current[peerId]=[];
    const initiator=u.uid<peerId; status(peerId,'connecting');
    s.getTracks().forEach(track=>{const sender=pc.addTrack(track,s);if(track.kind==='video'){const p=sender.getParameters();p.encodings=p.encodings?.length?p.encodings:[{}];p.encodings[0].maxBitrate=700000;p.encodings[0].maxFramerate=24;sender.setParameters(p).catch(()=>{})}});
    pc.ontrack=e=>{const rs=e.streams?.[0];if(rs){setRemoteStreams(x=>({...x,[peerId]:rs}));status(peerId,'connected')}};
    pc.onicecandidate=e=>{if(e.candidate)signal(peerId,'candidate',{candidate:e.candidate.toJSON()}).catch(console.error)};
    pc.onconnectionstatechange=()=>{const st=pc.connectionState;if(st==='connected')status(peerId,'connected');else if(st==='disconnected')status(peerId,'disconnected');else if(st==='failed'){status(peerId,'failed');if(initiator&&!retryRef.current[peerId]){retryRef.current[peerId]=setTimeout(()=>{delete retryRef.current[peerId];if(peersRef.current[peerId]===pc){closePeer(peerId);createPeer(peerId)}},1200)}}};
    pc.oniceconnectionstatechange=()=>{if(pc.iceConnectionState==='connected'||pc.iceConnectionState==='completed')status(peerId,'connected');if(pc.iceConnectionState==='failed'&&initiator)try{pc.restartIce()}catch{}};
    if(initiator){pc.onnegotiationneeded=async()=>{if(pc.signalingState!=='stable')return;try{await pc.setLocalDescription(await pc.createOffer());await signal(peerId,'offer',{sdp:pc.localDescription.sdp})}catch(e){console.error('offer failed',e)}}}
    return pc;
  };

  const startMedia=async()=>{if(streamRef.current)return streamRef.current;if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera and microphone are not available in this browser.');const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:640,max:1280},height:{ideal:360,max:720},frameRate:{ideal:24,max:24},facingMode:'user'},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=s;setLocalStream(s);setMic(s.getAudioTracks()[0]?.enabled??true);setCam(s.getVideoTracks()[0]?.enabled??true);return s};
  const startMeeting=async(id,displayName,isHost)=>{setBusy(true);setError('');try{await startMedia();await setDoc(doc(db,'rooms',id,'participants',userRef.current.uid),{participantId:userRef.current.uid,displayName,isHost,joinedAt:serverTimestamp()});setScreen('meeting')}catch(e){console.error(e);setError(e?.name==='NotAllowedError'?'Camera/microphone permission was blocked. Allow access and try again.':e?.message||'Could not start your camera and microphone.')}finally{setBusy(false)}};
  const createMeeting=async e=>{e.preventDefault();if(!ready||!userRef.current||!name.trim())return;setBusy(true);setError('');try{const id=generateRoomId();await setDoc(doc(db,'rooms',id),{status:'active',hostUid:userRef.current.uid,createdAt:serverTimestamp()});roomRef.current=id;setRoomId(id);setHost(true);history.replaceState({},'',`?room=${id}`);await startMeeting(id,name.trim(),true)}catch(e){console.error(e);setError('Could not create the meeting. Check Firebase and try again.');setBusy(false)}};
  const requestJoin=async e=>{e.preventDefault();if(!ready||!userRef.current||!roomRef.current||!name.trim())return;setBusy(true);setError('');if(host){await startMeeting(roomRef.current,name.trim(),true);return}try{const r=doc(db,'rooms',roomRef.current,'requests',userRef.current.uid);await setDoc(r,{displayName:name.trim(),status:'pending',createdAt:serverTimestamp()});setScreen('waiting');requestUnsubRef.current?.();requestUnsubRef.current=onSnapshot(r,async s=>{if(!s.exists())return;const st=s.data().status;if(st==='approved'){requestUnsubRef.current?.();requestUnsubRef.current=null;await startMeeting(roomRef.current,name.trim(),false)}else if(st==='denied'){requestUnsubRef.current?.();requestUnsubRef.current=null;setBusy(false);setScreen('denied')}})}catch(e){console.error(e);setError('That meeting is unavailable or the invite is invalid.');setBusy(false)}};

  useEffect(()=>{if(screen!=='meeting'||!roomId||!user)return;
    const roomUnsub=onSnapshot(doc(db,'rooms',roomId),s=>{if(s.exists()&&s.data().status==='ended')leaveMeeting('The host ended the meeting.',false)});
    const participantsUnsub=onSnapshot(collection(db,'rooms',roomId,'participants'),snap=>{const next={};snap.forEach(d=>next[d.id]=d.data());setParticipants(next);Object.keys(next).forEach(id=>{if(id!==user.uid&&user.uid<id&&!peersRef.current[id])createPeer(id)});Object.keys(peersRef.current).forEach(id=>{if(!next[id])closePeer(id)})});
    const signalsUnsub=onSnapshot(query(collection(db,'rooms',roomId,'signals'),where('to','==',user.uid)),async snap=>{for(const ch of snap.docChanges()){if(ch.type!=='added')continue;const ref=ch.doc, m=ch.data(),peerId=m.from;if(!SIGNAL_TYPES.has(m.type))continue;try{const pc=peersRef.current[peerId]||createPeer(peerId);if(!pc)continue;if(m.type==='candidate'){const c=new RTCIceCandidate(m.candidate);if(pc.remoteDescription)await pc.addIceCandidate(c);else(queuesRef.current[peerId]||(queuesRef.current[peerId]=[])).push(c)}else if(m.type==='offer'){if(pc.signalingState!=='stable'){await pc.setLocalDescription({type:'rollback'})}await pc.setRemoteDescription({type:'offer',sdp:m.sdp});for(const c of queuesRef.current[peerId]||[])await pc.addIceCandidate(c);queuesRef.current[peerId]=[];await pc.setLocalDescription(await pc.createAnswer());await signal(peerId,'answer',{sdp:pc.localDescription.sdp})}else if(m.type==='answer'&&pc.signalingState==='have-local-offer'){await pc.setRemoteDescription({type:'answer',sdp:m.sdp});for(const c of queuesRef.current[peerId]||[])await pc.addIceCandidate(c);queuesRef.current[peerId]=[]}await deleteDoc(ref)}catch(e){console.error('Signal processing failed',e)}}});
    let req=()=>{};if(host)req=onSnapshot(query(collection(db,'rooms',roomId,'requests'),where('status','==','pending')),s=>setPending(s.docs.map(d=>({id:d.id,...d.data()}))));
    return()=>{roomUnsub();participantsUnsub();signalsUnsub();req()};
  },[screen,roomId,user,host]);

  const allow=async id=>{try{await updateDoc(doc(db,'rooms',roomId,'requests',id),{status:'approved'});setPending(x=>x.filter(r=>r.id!==id))}catch(e){console.error(e)}};
  const deny=async id=>{try{await updateDoc(doc(db,'rooms',roomId,'requests',id),{status:'denied'});setPending(x=>x.filter(r=>r.id!==id))}catch(e){console.error(e)}};
  const leaveMeeting=async(reason='',home=true)=>{requestUnsubRef.current?.();requestUnsubRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());Object.keys(peersRef.current).forEach(closePeer);if(roomRef.current&&userRef.current)try{await deleteDoc(doc(db,'rooms',roomRef.current,'participants',userRef.current.uid))}catch{}streamRef.current=null;setLocalStream(null);setRemoteStreams({});setParticipants({});setPeerStatus({});setPending([]);setBusy(false);if(reason)setError(reason);if(home){setScreen(reason?'ended':'home');history.replaceState({},'',location.pathname)}};
  const endMeeting=async()=>{try{await updateDoc(doc(db,'rooms',roomId),{status:'ended'})}catch{}await leaveMeeting()};
  const toggleMic=()=>{const t=streamRef.current?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;setMic(t.enabled)}};const toggleCam=()=>{const t=streamRef.current?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;setCam(t.enabled)}};
  const copyInvite=async()=>{try{await navigator.clipboard.writeText(`${location.origin}?room=${roomId}`);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError('Could not copy the invite link.')}};
  const remoteIds=Object.keys(participants).filter(id=>id!==user?.uid),tileCount=Math.max(1,remoteIds.length+1);

  if(screen==='meeting')return <MeetingRoom name={name} host={host} roomId={roomId} localStream={localStream} remoteStreams={remoteStreams} participants={participants} peerStatus={peerStatus} remoteIds={remoteIds} tileCount={tileCount} mic={mic} cam={cam} pending={pending} copied={copied} onCopy={copyInvite} onToggleMic={toggleMic} onToggleCam={toggleCam} onLeave={()=>leaveMeeting()} onEnd={endMeeting} onAllow={allow} onDeny={deny}/>;
  return <div className="app-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><header className="landing-nav"><div className="brand"><span className="brand-mark"><Video size={18}/></span><span>Primora<span className="brand-accent">X</span></span></div><div className="nav-pill"><span className="live-dot"/> Private meetings</div></header><main className="landing-main">
    {screen==='home'&&<section className="hero-layout"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> Simple video meetings, without the clutter</div><h1>Meet face to face.<br/><span>Just send a link.</span></h1><p className="hero-text">Create a private room, invite your people, and start talking. No account, no downloads, no noise.</p><div className="trust-row"><span><Shield size={15}/> Invite-only</span><span><Wifi size={15}/> Peer-to-peer</span><span><Users size={15}/> Up to 4 people</span></div></div><EntryCard title="Start a meeting" subtitle="Create a room and share the invite with your team." icon={<Video size={23}/>} error={error}><form onSubmit={createMeeting}><label>Your name</label><div className="field-wrap"><UserRound size={18}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Sumukh" disabled={!ready||busy} required/></div><button className="primary-button" disabled={!ready||busy}>{busy?<><Loader2 className="spin" size={18}/> Starting...</>:<>Create meeting <ArrowRight size={18}/></>}</button></form><div className="card-note">You'll be the host and can approve who joins.</div></EntryCard></section>}
    {screen==='join'&&<section className="center-layout"><EntryCard title="Join the meeting" subtitle="Enter the name you'd like other participants to see." icon={<Link2 size={23}/>} error={error}><div className="join-top"><span className="small-kicker">INVITATION</span><span className="room-code">{roomId}</span></div><form onSubmit={requestJoin}><label>Your name</label><div className="field-wrap"><UserRound size={18}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Alex" disabled={!ready||busy} required/></div><button className="primary-button" disabled={!ready||busy}>{busy?<><Loader2 className="spin" size={18}/> Connecting...</>:host?<>Enter as host <ArrowRight size={18}/></>:<>Request to join <ArrowRight size={18}/></>}</button></form><button className="text-button" onClick={()=>{setScreen('home');setError('');history.replaceState({},'',location.pathname)}}>← Back</button></EntryCard></section>}
    {screen==='waiting'&&<StatusCard icon={<Loader2 className="spin" size={25}/>} title="Waiting for the host" text="Your request is with the host. Keep this tab open — we'll let you in automatically."/>}{screen==='denied'&&<StatusCard icon={<X size={25}/>} title="Request declined" text="The host didn't approve your request this time." action={<button className="secondary-button" onClick={()=>{setScreen('join');setError('')}}>Try again</button>}/>} {screen==='ended'&&<StatusCard icon={<PhoneOff size={25}/>} title="Meeting ended" text={error||'This meeting has finished.'} action={<button className="secondary-button" onClick={()=>{setScreen('home');setError('')}}>Back to home</button>}/>}</main></div>;
}

function EntryCard({title,subtitle,icon,error,children}){return <div className="entry-card"><div className="card-glow"/><div className="entry-icon">{icon}</div><h2>{title}</h2><p>{subtitle}</p>{error&&<div className="error-box">{error}</div>}{children}</div>}
function StatusCard({icon,title,text,action}){return <section className="center-layout"><div className="status-card"><div className="status-icon">{icon}</div><h2>{title}</h2><p>{text}</p>{action}</div></section>}
function MeetingRoom({name,host,roomId,localStream,remoteStreams,participants,peerStatus,remoteIds,tileCount,mic,cam,pending,copied,onCopy,onToggleMic,onToggleCam,onLeave,onEnd,onAllow,onDeny}){const [showRequests,setShowRequests]=useState(true);const connected=Object.values(peerStatus).filter(s=>s==='connected').length;const gridClass=useMemo(()=>`meeting-grid tiles-${Math.min(tileCount,4)}`,[tileCount]);return <div className="meeting-shell"><header className="meeting-topbar"><div className="meeting-brand"><span className="brand-mark small"><Video size={16}/></span><span>Primora<span className="brand-accent">X</span></span></div><div className="meeting-meta"><span className="status-live"><span className="live-dot"/> Live</span><span className="room-label">{roomId}</span><span className="people-count"><Users size={15}/> {tileCount}</span></div><button className="invite-button" onClick={onCopy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Invite'}</button></header><main className="meeting-stage"><div className={gridClass}><VideoTile stream={localStream} name={`${name} (You)`} local cam={cam} mic={mic} status="connected"/>{remoteIds.map(id=><VideoTile key={id} stream={remoteStreams[id]} name={participants[id]?.displayName||'Participant'} host={participants[id]?.isHost} cam={Boolean(remoteStreams[id])} mic status={peerStatus[id]||'connecting'}/>)}</div>{host&&pending.length>0&&showRequests&&<aside className="request-popover"><div className="request-head"><div><strong>Join requests</strong><span>{pending.length} waiting</span></div><button onClick={()=>setShowRequests(false)}><X size={17}/></button></div>{pending.map(r=><div className="request-row" key={r.id}><div className="request-avatar">{r.displayName?.charAt(0)?.toUpperCase()||'P'}</div><div className="request-person"><strong>{r.displayName}</strong><span>wants to join</span></div><div className="request-actions"><button className="approve" onClick={()=>onAllow(r.id)}><UserCheck size={16}/></button><button className="reject" onClick={()=>onDeny(r.id)}><UserX size={16}/></button></div></div>)}</aside>}{host&&pending.length>0&&!showRequests&&<button className="request-bubble" onClick={()=>setShowRequests(true)}><Users size={16}/> {pending.length} request{pending.length>1?'s':''}</button>}<div className="connection-pill"><span className={`connection-dot ${connected>0?'good':''}`}/>{connected>0?`${connected} connected`:tileCount===1?'Waiting for people':'Connecting...'}</div></main><footer className="meeting-controls"><div className="control-group"><ControlButton active={mic} onClick={onToggleMic} icon={mic?<Mic/>:<MicOff/>} label={mic?'Mute':'Unmute'}/><ControlButton active={cam} onClick={onToggleCam} icon={cam?<Video/>:<VideoOff/>} label={cam?'Camera':'Camera off'}/></div><button className="leave-button" onClick={onLeave}><PhoneOff size={19}/><span>Leave</span></button>{host&&<button className="end-button" onClick={onEnd}>End meeting</button>}</footer></div>}
function ControlButton({icon,label,active,onClick}){return <button className={`control-button ${active?'':'off'}`} onClick={onClick}><span>{icon}</span><small>{label}</small></button>}
function VideoTile({stream,name,host,local,cam,mic,status}){const ref=useRef(null),[needsPlay,setNeedsPlay]=useState(false);useEffect(()=>{const v=ref.current;if(!v||!stream)return;v.srcObject=stream;const play=()=>v.play().then(()=>setNeedsPlay(false)).catch(()=>setNeedsPlay(true));v.onloadedmetadata=play;play();return()=>{v.onloadedmetadata=null}},[stream]);const initial=name?.replace(' (You)','').trim().charAt(0).toUpperCase()||'P';return <article className="video-tile">{stream&&cam?<video ref={ref} autoPlay playsInline muted={local} className={local?'mirrored':''} onClick={()=>ref.current?.play().catch(()=>{})}/>:<div className="avatar-view"><div className="avatar-large">{initial}</div><span>{status==='failed'?'Connection failed':status==='connecting'?'Connecting…':'Camera off'}</span></div>}<div className="tile-shade"/><div className="tile-label"><span className="tile-name">{name}{host&&<Shield size={13}/>}</span><span className="tile-mic">{mic?<Mic size={13}/>:<MicOff size={13}/>}</span></div>{needsPlay&&!local&&<button className="tap-audio" onClick={()=>ref.current?.play().then(()=>setNeedsPlay(false))}>Tap to play audio</button>}</article>}
